server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bytebank-accounts
          uri: lb://bytebank-accounts
          predicates:
            - Path=/api/v2/accounts/**

        - id: bytebank-customer
          uri: lb://bytebank-customer
          predicates:
            - Path=/api/v2/customers/**

        - id: bytebank-transactions
          uri: lb://bytebank-transactions
          predicates:
            - Path=/api/v2/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true