server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  lifecycle:
    timeout-per-shutdown-phase: 30s

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: bytebank-accounts
          uri: lb://BYTEBANK-ACCOUNTS
          predicates:
            - Path=/api/v1/accounts/**

        - id: bytebank-customer
          uri: lb://BYTEBANK-CUSTOMER
          predicates:
            - Path=/api/v2/customers/**

        - id: bytebank-transactions
          uri: lb://BYTEBANK-TRANSACTIONS
          predicates:
            - Path=/api/v1/transactions/**

        - id: bytebank-notification
          uri: lb://BYTEBANK-NOTIFICATION
          predicates:
            - Path=/api/v1/notifications/**

        - id: bytebank-accounts-docs
          uri: lb://BYTEBANK-ACCOUNTS
          predicates:
            - Path=/bytebank-accounts/v3/api-docs
          filters:
            - RewritePath=/bytebank-accounts/v3/api-docs, /v3/api-docs

        - id: bytebank-customer-docs
          uri: lb://BYTEBANK-CUSTOMER
          predicates:
            - Path=/bytebank-customer/v3/api-docs
          filters:
            - RewritePath=/bytebank-customer/v3/api-docs, /v3/api-docs

        - id: bytebank-transactions-docs
          uri: lb://BYTEBANK-TRANSACTIONS
          predicates:
            - Path=/bytebank-transactions/v3/api-docs
          filters:
            - RewritePath=/bytebank-transactions/v3/api-docs, /v3/api-docs

        - id: bytebank-notification-docs
          uri: lb://BYTEBANK-NOTIFICATION
          predicates:
            - Path=/bytebank-notification/v3/api-docs
          filters:
            - RewritePath=/bytebank-notification/v3/api-docs, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Accounts Service
        url: /bytebank-accounts/v3/api-docs

      - name: Customer Service
        url: /bytebank-customer/v3/api-docs
      - name: Transactions Service
        url: /bytebank-transactions/v3/api-docs
      - name: Notification Service
        url: /bytebank-notification/v3/api-docs
    display-request-duration: true
  override-with-generic-response: false