server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
          - id: bytebank-accounts
            uri: lb://bytebank-accounts
            predicates:
              - Path=/api/v1/accounts/**

          - id: bytebank-customer
            uri: lb://bytebank-customer
            predicates:
              - Path=/api/v2/customers/**

          - id: bytebank-transactions
            uri: lb://bytebank-transactions
            predicates:
              - Path=/api/v1/transactions/**

          - id: bytebank-notification
            uri: lb://bytebank-notification
            predicates:
              - Path=/api/v1/notifications/**

            #Finance-AI-Service
          - id: finance-ai-audio
            uri: lb://finance-ai-service
            predicates:
              - Path=/api/v1/operations/audio,/api/v1/operations/whatsapp
            filters:
              - ResolveUser

          - id: finance-ai-service
            uri: lb://finance-ai-service
            predicates:
              - Path=/api/v1/operations/**

          - id: bytebank-accounts-docs
            uri: lb://bytebank-accounts
            predicates:
              - Path=/bytebank-accounts/v3/api-docs
            filters:
              - RewritePath=/bytebank-accounts/v3/api-docs, /v3/api-docs

          - id: bytebank-customer-docs
            uri: lb://bytebank-customer
            predicates:
              - Path=/bytebank-customer/v3/api-docs
            filters:
              - RewritePath=/bytebank-customer/v3/api-docs, /v3/api-docs

          - id: bytebank-transactions-docs
            uri: lb://bytebank-transactions
            predicates:
              - Path=/bytebank-transactions/v3/api-docs
            filters:
              - RewritePath=/bytebank-transactions/v3/api-docs, /v3/api-docs

          - id: bytebank-notification-docs
            uri: lb://bytebank-notification
            predicates:
              - Path=/bytebank-notification/v3/api-docs
            filters:
              - RewritePath=/bytebank-notification/v3/api-docs, /v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

    management:
      zipkin:
        tracing:
          endpoint: http://localhost:9411/api/v2/spans